# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: seeeduino_xiao_ble
    shield: hillside46_dongle_screen
    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
    snippet: zmk-usb-logging
    artifact-name: hillside46_dongle_screen
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: hillside46_dongle_screen-settings-reset
  - board: nice_nano_v2
    shield: hillside46_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: hillside46_left
  - board: nice_nano_v2
    shield: hillside46_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: hillside46_right
#  - board: seeeduino_xiao_ble
#    shield: settings_reset
#  - board: nice_nano_v2
#    shield: settings_reset
